steps:
  - label: ":julia: Run tests on Julia v1 with Intel oneAPI"
    env:
      GROUP: ONEAPI
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
          persist_depot_dirs: ""
      - JuliaCI/julia-test#v1:
           coverage: false # 1000x slowdown
    agents:
      queue: "juliagpu"
      intel: "*"
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/
  
  - label: ":julia: Run tests on Julia v1 with AMD ROCm"
    env:
      GROUP: ROCM
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
          persist_depot_dirs: ""
      - JuliaCI/julia-test#v1:
           coverage: false # 1000x slowdown
    agents:
      queue: "juliagpu"
      rocm: "*"
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: "..."
